### PR TITLE
update bundletool

### PR DESCRIPTION
**Pull request by jpike88**
hi @Ribeiro-Tiago can you merge and publish this lib? I want to propagate the updated libs to apkup :)

### CODE REVIEW

**Comment by Ribeiro-Tiago** [comment]
Thanks for the reminder. I meant to update it yesterday but completely forgot

**Comment by jpike88** [comment]
thanks, legend!

**Comment by Ribeiro-Tiago** [comment]
v1.0.1 up and running on npm, feel free to update apkup

**Comment by jpike88** [comment]
thanks I've lodged an issue with them

**Pull request merged**
